# Generated by Django 3.1.4 on 2021-04-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='date_posted',
        ),
    ]
